public enum Word {
    INHERITANCE ("THE OBJECT-ORIENTED WAY TO BECOME WEALTHY"), ENCAPSULATION ("SENSITIVE DATA CAN'T BE SEEN"), POLYMORPHISM ("THE ABILITY OF AN OBJECT TO TAKE ON MANY FORMS"), ABSTRACTION("IT'S CLEAR WHAT OBJECT DOES, NOT HOW IT DOES IT"), INTERFACE("FORMS A CONTRACT BETWEEN THE CLASS AND THE OUTSIDE WORLD"), OBJECT("IT HAS STATE AND BEHAVIOR"),INTELLIJ("FROM TEKBEANS FELLOW MEMBER: VISUAL STUDIO IS A NICE HOTEL, AND X IS A LUXURY RESORT. WHAT IS IT?");
    final String description;
    Word(String desc){
        this.description = desc;
    }
}
